### ISSUE TITLE
SIGSEGV on Ubuntu 18.04 (Volt 0.80)

### ISSUE THREAD

**Issue by AndreRenaud** [eul-im/eul#142]
Volt crashes on startup for me:
andre@andre-Z270M-D3H:~/Downloads$ gdb ./volt 
GNU gdb (Ubuntu 8.1-0ubuntu3) 8.1.0.20180409-git
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./volt...(no debugging symbols found)...done.
(gdb) r
Starting program: /home/andre/Downloads/volt 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffea0ca700 (LWP 31366)]
[New Thread 0x7fffe98c9700 (LWP 31367)]
[Thread 0x7fffea0ca700 (LWP 31366) exited]
[New Thread 0x7fffe8955700 (LWP 31368)]
[Thread 0x7fffe8955700 (LWP 31368) exited]
[New Thread 0x7fffe8955700 (LWP 31375)]
[Thread 0x7fffe8955700 (LWP 31375) exited]
[Thread 0x7fffe98c9700 (LWP 31367) exited]
[New Thread 0x7fffe8955700 (LWP 31376)]

Thread 6 "volt" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffe8955700 (LWP 31376)]
0x000000000043da8a in os.read_file ()
(gdb) where
#0  0x000000000043da8a in os.read_file ()
#1  0x0000000000442274 in f_307 ()
#2  0x0000000000432609 in f_554 ()
#3  0x00007ffff761b6db in start_thread (arg=0x7fffe8955700)
    at pthread_create.c:463
#4  0x00007ffff6bf488f in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

andre@andre-Z270M-D3H:~/Downloads$ valgrind ./volt 
==31264== Memcheck, a memory error detector
==31264== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==31264== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==31264== Command: ./volt
==31264== 
==31264== Thread 2:
==31264== Argument 'size' of function malloc has a fishy (possibly negative) value: -9223372036854775808
==31264==    at 0x4C2FB0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==31264==    by 0x43DA6B: ??? (in /home/andre/Downloads/volt)
==31264==    by 0x4: ???
==31264==    by 0x1D: ???
==31264==    by 0x1B30246F: ???
==31264==    by 0x442273: ??? (in /home/andre/Downloads/volt)
==31264==    by 0x800000003: ???
==31264==    by 0xF: ???
==31264==    by 0x1B30261F: ???
==31264==    by 0xD5BA67F: ???
==31264==    by 0x16C06FBF: ???
==31264== 
==31264== Syscall param read(buf) points to unaddressable byte(s)
==31264==    at 0x5E5D0B4: read (read.c:27)
==31264==    by 0x5DD8671: _IO_file_xsgetn (fileops.c:1364)
==31264==    by 0x5DD7493: fread_unlocked (iofread_u.c:40)
==31264==    by 0x43DA81: ??? (in /home/andre/Downloads/volt)
==31264==    by 0x4: ???
==31264==    by 0x1D: ???
==31264==    by 0x1B30246F: ???
==31264==    by 0x442273: ??? (in /home/andre/Downloads/volt)
==31264==    by 0x800000003: ???
==31264==    by 0xF: ???
==31264==    by 0x1B30261F: ???
==31264==    by 0xD5BA67F: ???
==31264==  Address 0x0 is not stack'd, malloc'd or (recently) free'd
==31264== 
==31264== Invalid write of size 1
==31264==    at 0x43DA8A: ??? (in /home/andre/Downloads/volt)
==31264==    by 0x4: ???
==31264==    by 0x1D: ???
==31264==    by 0x1B30246F: ???
==31264==    by 0x442273: ??? (in /home/andre/Downloads/volt)
==31264==    by 0x800000003: ???
==31264==    by 0xF: ???
==31264==    by 0x1B30261F: ???
==31264==    by 0xD5BA67F: ???
==31264==    by 0x16C06FBF: ???
==31264==  Address 0x7fffffffffffffff is not stack'd, malloc'd or (recently) free'd
==31264== 
==31264== 
==31264== Process terminating with default action of signal 11 (SIGSEGV)
==31264==  General Protection Fault
==31264==    at 0x43DA8A: ??? (in /home/andre/Downloads/volt)
==31264==    by 0x4: ???
==31264==    by 0x1D: ???
==31264==    by 0x1B30246F: ???
==31264==    by 0x442273: ??? (in /home/andre/Downloads/volt)
==31264==    by 0x800000003: ???
==31264==    by 0xF: ???
==31264==    by 0x1B30261F: ???
==31264==    by 0xD5BA67F: ???
==31264==    by 0x16C06FBF: ???
==31264== 
==31264== HEAP SUMMARY:
==31264==     in use at exit: 137,826,105 bytes in 9,149 blocks
==31264==   total heap usage: 66,235 allocs, 57,086 frees, 975,706,232 bytes allocated
==31264== 
==31264== LEAK SUMMARY:
==31264==    definitely lost: 6,810 bytes in 168 blocks
==31264==    indirectly lost: 28,681 bytes in 85 blocks
==31264==      possibly lost: 44,317,065 bytes in 403 blocks
==31264==    still reachable: 93,473,549 bytes in 8,493 blocks
==31264==                       of which reachable via heuristic:
==31264==                         newarray           : 16 bytes in 1 blocks
==31264==                         multipleinheritance: 104 bytes in 1 blocks
==31264==         suppressed: 0 bytes in 0 blocks
==31264== Rerun with --leak-check=full to see details of leaked memory
==31264== 
==31264== For counts of detected and suppressed errors, rerun with: -v
==31264== ERROR SUMMARY: 3 errors from 3 contexts (suppressed: 0 from 0)
Segmentation fault (core dumped)

**Comment by zajca** [comment]
Can confirm same issue on Archlinux with wayland

[strace.txt](https://github.com/voltapp/volt/files/3053299/strace.txt)
[valgrid.txt](https://github.com/voltapp/volt/files/3053300/valgrid.txt)
[gdb.txt](https://github.com/voltapp/volt/files/3053308/gdb.txt)

**Comment by OmriSama** [comment]
Getting a segfault on Ubuntu 18.04 as well; latest Volt.
